import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml",
]

[font.normal]
family = "Inconsolata Nerd Font"

[font]
size = 18.0

[window]
option_as_alt = "OnlyLeft"

[shell] 
program = "/opt/homebrew/bin/tmux"